# Generated by Django 6.0.5 on 2026-06-03 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajlasmaAlanı',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oluşturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('katılımcılar', models.ManyToManyField(related_name='mesajlaşma_alanları', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('gönderilme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gönderici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesajlaşma_alanı', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='api.mesajlasmaalanı')),
            ],
        ),
    ]
