# Generated by Django 6.0.5 on 2026-06-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaj',
            old_name='mesajlaşma_alanı',
            new_name='mesajlasma_alanı',
        ),
        migrations.RenameField(
            model_name='mesajlasmaalanı',
            old_name='oluşturulma_tarihi',
            new_name='olusturulma_tarihi',
        ),
    ]
