# Generated by Django 6.0.5 on 2026-06-03 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_mesajlaşma_alanı_mesaj_mesajlasma_alanı_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajlasmaalanı',
            name='katılımcılar',
            field=models.ManyToManyField(related_name='mesajlasma_alanları', to=settings.AUTH_USER_MODEL),
        ),
    ]
