# Generated by Django 6.0.5 on 2026-06-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mesajlasmaalanı_katılımcılar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesajlasmaalanı',
            name='isim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
